import fs from "fs/promises";
import { z } from "zod";
import { createHash } from "node:crypto";
import { ZBuildInfo, ZContractInfo, toAsyncResult } from "../utils";
import { LOG_COLORS, retrieveFreshBuildInfo, ScriptError } from "./utils";

/**
 * This script generates the differences between the artifacts generated by a fresh compilation and the ones of the `latest` release.
 *
 * The fresh artifacts are represented by the file at `artifacts/build-info/<build info hash>.json`.
 * The `latest` artifacts are represented by the file at `releases/latest/build-info.json`.
 *
 * For each build info file, the script will parse the `output.contracts` object.
 * This object contains as keys the path of a contract file and as values the contracts within it, i.e.
 * ```
 * {
 *  "output": {
 *   "contracts": {
 *      "path/to/foo.sol": {
 *         "Foo": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         }
 *      },
 *      "path/to/bar.sol": {
 *         "Bar1": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *         "Bar2": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *      },
 *   }
 * }
 * ```
 *
 * For each contract, a hash is computed based on
 * - stringified abi,
 * - bytecode object,
 * - metadata
 * This hash is stored in a map with the `<file path>-<contract name>` as key.
 *
 * Comparing the two maps, the script will output the differences between the two sets of contracts.
 */
type Difference = {
  path: string;
  name: string;
  status: "added" | "removed" | "changed";
};
export async function generateDiffWithLatest(
  opts: { debug?: boolean } = {},
): Promise<Difference[]> {
  const freshBuildInfoResult = await toAsyncResult(retrieveFreshBuildInfo());
  if (!freshBuildInfoResult.success) {
    throw new ScriptError(
      `Error retrieving the build info for the compilation. Please, make sure to have a unique build info file in the "artifacts/build-info" folder.`,
    );
  }

  const virtualReleaseContractHashesResult = await toAsyncResult(
    generateContractHashes(freshBuildInfoResult.value.content),
    { debug: opts.debug },
  );

  if (!virtualReleaseContractHashesResult.success) {
    throw new Error(
      `Error generating virtual release contract hashes: ${virtualReleaseContractHashesResult.error}`,
    );
  }

  const LATEST_RELEASE_PATH = "releases/latest/build-info.json";
  const hasLatestRelease = await fs
    .stat(LATEST_RELEASE_PATH)
    .catch(() => false);
  if (!hasLatestRelease) {
    console.log(
      LOG_COLORS.warn,
      'The "latest" release has not been found locally. All contracts are considered as added. If this is not expected, please run the `pull` command first.',
    );
    const differences: Difference[] = [];
    for (const contractKey of virtualReleaseContractHashesResult.value.keys()) {
      const { contractPath, contractName } = parseKey(contractKey);
      differences.push({
        path: contractPath,
        name: contractName,
        status: "added",
      });
    }
    return differences;
  }

  const latestReleaseBuildInfoContentResult = await toAsyncResult(
    fs.readFile(LATEST_RELEASE_PATH, "utf-8"),
    { debug: opts.debug },
  );
  if (!latestReleaseBuildInfoContentResult.success) {
    throw new Error(
      `Error reading latest release build info: ${latestReleaseBuildInfoContentResult.error}`,
    );
  }

  const latestReleaseContractHashesResult = await toAsyncResult(
    generateContractHashes(latestReleaseBuildInfoContentResult.value),
    { debug: opts.debug },
  );
  if (!latestReleaseContractHashesResult.success) {
    throw new Error(
      `Error generating latest release contract hashes: ${latestReleaseContractHashesResult.error}`,
    );
  }

  const differences: Difference[] = [];
  for (const [
    contractKey,
    contractHash,
  ] of virtualReleaseContractHashesResult.value.entries()) {
    const { contractPath, contractName } = parseKey(contractKey);
    const latestReleaseHash =
      latestReleaseContractHashesResult.value.get(contractKey);
    if (!latestReleaseHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "added",
      });
    } else if (latestReleaseHash !== contractHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "changed",
      });
    }
  }

  for (const contractKey of latestReleaseContractHashesResult.value.keys()) {
    if (!virtualReleaseContractHashesResult.value.has(contractKey)) {
      const { contractPath, contractName } = parseKey(contractKey);
      differences.push({
        path: contractPath,
        name: contractName,
        status: "removed",
      });
    }
  }

  return differences;
}

async function generateContractHashes(
  buildInfoContent: string,
): Promise<Map<string, string>> {
  const buildInfoResult = ZBuildInfo.safeParse(JSON.parse(buildInfoContent));
  if (!buildInfoResult.success) {
    throw new Error(`Invalid build info file: ${buildInfoResult.error}`);
  }

  const contractHashes = new Map<string, string>();
  for (const contractPath in buildInfoResult.data.output.contracts) {
    const contracts = buildInfoResult.data.output.contracts[contractPath];
    for (const contractName in contracts) {
      const contract = contracts[contractName];
      const hash = hashContract(contract);
      contractHashes.set(formKey(contractPath, contractName), hash);
    }
  }

  return contractHashes;
}

function hashContract(contract: z.infer<typeof ZContractInfo>): string {
  const hash = createHash("sha256");

  contract.abi.sort((a, b) => a.name.localeCompare(b.name));
  for (const abiItem of contract.abi) {
    hash.update(JSON.stringify(abiItem));
  }

  hash.update(contract.evm.bytecode.object);
  hash.update(contract.metadata);

  return hash.digest("hex");
}

const SEPARATOR = "@@@@";
function formKey(contractPath: string, contractName: string): string {
  return `${contractPath}${SEPARATOR}${contractName}`;
}
function parseKey(key: string): { contractPath: string; contractName: string } {
  const [contractPath, contractName] = key.split(SEPARATOR);
  if (!contractPath || !contractName) {
    throw new Error(`Invalid key: ${key}`);
  }
  return { contractPath, contractName };
}
