// THIS IS AN AUTOGENERATED FILE. EDIT AT YOUR OWN RISKS.

export const CONTRACTS = {
  "src/Counter.sol/Counter": ["latest", "v1.3.1"],
  "src/IncrementOracle.sol/IncrementOracle": ["latest", "v1.3.1"],
} as const;

export const RELEASES = {
  latest: [
    "src/Counter.sol/Counter",
    "src/IncrementOracle.sol/IncrementOracle",
  ],
  "v1.3.1": [
    "src/Counter.sol/Counter",
    "src/IncrementOracle.sol/IncrementOracle",
  ],
} as const;
