name: Main worflow

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    name: Format and lint check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
  release:
    name: Upload latest release artifacts and release NPM package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn
      - name: Create artifacts
        run: yarn compile
      - name: "Push latest release to S3"
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-3
        run: yarn cli push latest
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # Script to run logic logic before actually publishing
          # This is needed as Changesets won't trigger the tags workflow when a new version is published, so we need to do it manually
          # The steps of the script are:
          # 1. Upload the compilation artifact to S3 with the new release tag,
          # 2. Download the releases,
          # 3. Build the artifacts for the NPM package,
          # 4. Publish the NPM package
          publish: yarn release
        env:
          BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
