name: Pull Request workflow

on:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  simulate-release:
    name: "Simulate Release"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13
      - name: Install dependencies
        run: yarn
      - name: Create temporary release artifacts
        run: yarn compile
      - name: Compile scripts
        run: yarn scripts:compile
      - name: Create diff between artifacts and latest release
        uses: actions/github-script@v7
        id: artifacts-diff
        with:
          script: |
            const { generateDiffWithLatest } = await import('${{ github.workspace }}/dist/diff-with-latest.js');
            const diff = await generateDiffWithLatest();
            return diff;
      - name: Create or update comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const existingBotComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Release Plan Output')
            });
            // 2. Create new comment with diff
            console.log(typeof ${{ steps.artifacts-diff.outputs.result }}); // Debugging
            let output = "#### Release Plan Output";
            if (${{ steps.artifacts-diff.outputs.result }}.length === 0) {
              output += "\nNo changes detected in the release artifacts.";
            } else {
              output += "\n```";
              for (const diff of ${{ steps.artifacts-diff.outputs.result }}) {
                output += "\n";
                output += `- ${diff.name} (${diff.path}): ${diff.status}`;
              }
              output += "\n```";
            }
            output += "\n\nComparison is made between the latest release artifacts and the current artifacts generated from the PR code."
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
            // 3. Delete previous comment so PR timeline makes sense
            if (existingBotComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingBotComment.id,
              });
            }
      - name: Commit latest release artifacts
        run: |
          build_info_filename=$(ls -AU artifacts/build-info | head -1)
          mkdir -p releases/latest
          cp -r artifacts/build-info/$build_info_filename releases/latest/build-info.json
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update latest release artifacts"
          git push
