name: Pull Request workflow

on:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  simulate-release:
    name: "Simulate Release"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13
      - name: Install dependencies
        run: yarn
      - name: Create temporary release artifacts
        run: yarn compile
      - name: Create diff between artifacts and latest release
        uses: actions/github-script@v7
        with:
          script: |
            const { generateDiffWithLatest } = await import('${{ github.workspace }}/scripts/v2-exploration/diff-with-latest.ts');
            const diff = await generateDiffWithLatest();
            console.log(diff);
