name: Releases workflow

on:
  push:
    tags:
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  upload-release-artifacts:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn
      - name: Create artifacts
        run: yarn compile
      - name: Push release to S3
        run: yarn hardhat soko push --release ${{ github.ref_name }}
