name: Releases workflow

on:
  push:
    tags:
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  upload-release-artifacts:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn
      - name: Create artifacts
        run: yarn compile
      - name: Push release to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-3
        run: yarn cli push ${{ github.ref_name }}
